In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib notebook
from datetime import datetime, timedelta

In [2]:
customer_acqusition = pd.read_csv("C:/Users/shubh dwivedi/Downloads/Python Foundation Case Study 2 - Credit Card Case Study/Customer Acqusition.csv")
customer_acqusition

     No Customer  Age        City   Product     Limit Company        Segment
0     1       A1   76   BANGALORE      Gold  500000.0      C1  Self Employed
1     2       A2   71    CALCUTTA    Silver  100000.0      C2   Salaried_MNC
2     3       A3   34      COCHIN  Platimum   10000.0      C3   Salaried_Pvt
3     4       A4   47      BOMBAY  Platimum   10001.0      C4           Govt
4     5       A5   56   BANGALORE  Platimum   10002.0      C5  Normal Salary
..  ...      ...  ...         ...       ...       ...     ...            ...
95   96      A96   54     CHENNAI    Silver  100000.0     C19   Salaried_Pvt
96   97      A97   58  TRIVANDRUM  Platimum   10000.0     C20           Govt
97   98      A98   51    CALCUTTA  Platimum   10001.0     C21  Normal Salary
98   99      A99   35    CALCUTTA  Platimum   10002.0     C22  Self Employed
99  100     A100   36      COCHIN    Silver  100000.0      C5   Salaried_MNC

[100 rows x 8 columns]

In [3]:
repayment = pd.read_csv("C:/Users/shubh dwivedi/Downloads/Python Foundation Case Study 2 - Credit Card Case Study/Repayment.csv")
repayment

      SL No: Customer      Month     Amount  Unnamed: 4
0        NaN       A1  12-Jan-04  495414.75         NaN
1        2.0       A1   3-Jan-04  245899.02         NaN
2        3.0       A1  15-Jan-04  259490.06         NaN
3        4.0       A1  25-Jan-04  437555.12         NaN
4        5.0       A1  17-Jan-05  165972.88         NaN
...      ...      ...        ...        ...         ...
1518     NaN      NaN        NaN        NaN         NaN
1519     NaN      NaN        NaN        NaN         NaN
1520     NaN      NaN        NaN        NaN         NaN
1521     NaN      NaN        NaN        NaN         NaN
1522     NaN      NaN        NaN        NaN         NaN

[1523 rows x 5 columns]

In [4]:
repayment.drop(columns='Unnamed: 4',inplace=True)

In [5]:
repayment

      SL No: Customer      Month     Amount
0        NaN       A1  12-Jan-04  495414.75
1        2.0       A1   3-Jan-04  245899.02
2        3.0       A1  15-Jan-04  259490.06
3        4.0       A1  25-Jan-04  437555.12
4        5.0       A1  17-Jan-05  165972.88
...      ...      ...        ...        ...
1518     NaN      NaN        NaN        NaN
1519     NaN      NaN        NaN        NaN
1520     NaN      NaN        NaN        NaN
1521     NaN      NaN        NaN        NaN
1522     NaN      NaN        NaN        NaN

[1523 rows x 4 columns]

In [6]:
repayment.drop(columns='SL No:',inplace=True)

In [7]:
repayment

     Customer      Month     Amount
0          A1  12-Jan-04  495414.75
1          A1   3-Jan-04  245899.02
2          A1  15-Jan-04  259490.06
3          A1  25-Jan-04  437555.12
4          A1  17-Jan-05  165972.88
...       ...        ...        ...
1518      NaN        NaN        NaN
1519      NaN        NaN        NaN
1520      NaN        NaN        NaN
1521      NaN        NaN        NaN
1522      NaN        NaN        NaN

[1523 rows x 3 columns]

In [8]:
repayment.dropna(axis=0,inplace=True)
repayment

     Customer      Month     Amount
0          A1  12-Jan-04  495414.75
1          A1   3-Jan-04  245899.02
2          A1  15-Jan-04  259490.06
3          A1  25-Jan-04  437555.12
4          A1  17-Jan-05  165972.88
...       ...        ...        ...
1495      A67   9-May-05   55638.77
1496      A68  10-May-06  319836.49
1497      A69  11-Jul-06  247628.45
1498      A70  12-Aug-05  454016.51
1499      A71  13-Sep-04   56286.33

[1500 rows x 3 columns]

In [9]:
spend = pd.read_csv("C:/Users/shubh dwivedi/Downloads/Python Foundation Case Study 2 - Credit Card Case Study/spend.csv")
spend

      Sl No: Customer      Month        Type     Amount
0          1       A1  12-Jan-04   JEWELLERY  485470.80
1          2       A1   3-Jan-04       PETRO  410556.13
2          3       A1  15-Jan-04     CLOTHES   23740.46
3          4       A1  25-Jan-04        FOOD  484342.47
4          5       A1  17-Jan-05      CAMERA  369694.07
...      ...      ...        ...         ...        ...
1495    1496      A67   4-Feb-06  BUS TICKET  356872.73
1496    1497      A68  25-Mar-06  BUS TICKET  204971.10
1497    1498      A69  31-Mar-06  BUS TICKET   50449.44
1498    1499      A70  23-Mar-06  BUS TICKET   80593.94
1499    1500      A71  24-Mar-06  BUS TICKET  194447.62

[1500 rows x 5 columns]

#### 1. In the above dataset,
##### a. In case age is less than 18, replace it with mean of age value

In [10]:
customer_acqusition[customer_acqusition['Age']<18] = np.mean(customer_acqusition['Age'])

In [11]:
customer_acqusition.head(20)

,No,Customer,Age,City,Product,Limit,Company,Segment
0,1.00,A1,76.00,BANGALORE,Gold,500000.00,C1,Self Employed
1,2.00,A2,71.00,CALCUTTA,Silver,100000.00,C2,Salaried_MNC
2,3.00,A3,34.00,COCHIN,Platimum,10000.00,C3,Salaried_Pvt
3,4.00,A4,47.00,BOMBAY,Platimum,10001.00,C4,Govt
4,5.00,A5,56.00,BANGALORE,Platimum,10002.00,C5,Normal Salary
5,6.00,A6,70.00,DELHI,Silver,100000.00,C6,Self Employed
6,7.00,A7,26.00,COCHIN,Silver,100001.00,C7,Salaried_MNC
7,8.00,A8,67.00,PATNA,Silver,100002.00,C8,Salaried_Pvt
8,9.00,A9,79.00,CHENNAI,Silver,100003.00,C9,Govt
9,10.00,A10,54.00,CALCUTTA,Gold,500000.00,C10,Normal Salary
10,11.00,A11,35.00,COCHIN,Gold,500000.00,C11,Normal Salary
11,12.00,A12,51.00,BOMBAY,Gold,500000.00,C12,Self Employed
12,13.00,A13,29.00,BANGALORE,Gold,500000.00,C13,Salaried_MNC
13,46.49,46.49,46.49,46.49,46.49,46.49,46.49,46.49
14,15.00,A15,25.00,CALCUTTA,Gold,500000.00,C15,Govt
15,16.00,A16,52.00,COCHIN,Gold,500000.00,C16,Normal Salary
16,17.00,A17,78.00,BOMBAY,Gold,500000.00,C17,Self Employed
17,18.00,A18,34.00,BANGALORE,Silver,100000.00,C18,Salaried_MNC
18,19.00,A19,27.00,BANGALORE,Platimum,10000.00,C19,Salaried_Pvt
19,20.00,A20,27.00,CALCUTTA,Platimum,10001.00,C20,Govt

####  b. In case spend amount is more than the limit, replace it with 50% of that customerâ€™s limit.

In [12]:
customer_spend = pd.merge(left=customer_acqusition, right=spend,on='Customer',how = 'inner')
customer_spend

,No,Customer,Age,City,Product,Limit,Company,Segment,Sl No:,Month,Type,Amount
0,1.0,A1,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,1,12-Jan-04,JEWELLERY,485470.80
1,1.0,A1,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,2,3-Jan-04,PETRO,410556.13
2,1.0,A1,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,3,15-Jan-04,CLOTHES,23740.46
3,1.0,A1,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,4,25-Jan-04,FOOD,484342.47
4,1.0,A1,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,5,17-Jan-05,CAMERA,369694.07
...,...,...,...,...,...,...,...,...,...,...,...,...
1425,96.0,A96,54.0,CHENNAI,Silver,100000.0,C19,Salaried_Pvt,98,25-Jan-04,BIKE,54729.66
1426,97.0,A97,58.0,TRIVANDRUM,Platimum,10000.0,C20,Govt,99,12-Jan-04,AUTO,139018.26
1427,98.0,A98,51.0,CALCUTTA,Platimum,10001.0,C21,Normal Salary,100,3-Jan-04,SHOPPING,284521.06
1428,99.0,A99,35.0,CALCUTTA,Platimum,10002.0,C22,Self Employed,101,15-Jan-04,AIR TICKET,90184.22
1429,100.0,A100,36.0,COCHIN,Silver,100000.0,C5,Salaried_MNC,102,25-Jan-04,BUS TICKET,224786.88

In [13]:
customer_spend['Amount']=np.where(customer_spend['Amount']>customer_spend['Limit'],customer_spend['Limit']/2,customer_spend['Amount'])  
customer_spend

,No,Customer,Age,City,Product,Limit,Company,Segment,Sl No:,Month,Type,Amount
0,1.0,A1,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,1,12-Jan-04,JEWELLERY,485470.80
1,1.0,A1,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,2,3-Jan-04,PETRO,410556.13
2,1.0,A1,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,3,15-Jan-04,CLOTHES,23740.46
3,1.0,A1,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,4,25-Jan-04,FOOD,484342.47
4,1.0,A1,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,5,17-Jan-05,CAMERA,369694.07
...,...,...,...,...,...,...,...,...,...,...,...,...
1425,96.0,A96,54.0,CHENNAI,Silver,100000.0,C19,Salaried_Pvt,98,25-Jan-04,BIKE,54729.66
1426,97.0,A97,58.0,TRIVANDRUM,Platimum,10000.0,C20,Govt,99,12-Jan-04,AUTO,5000.00
1427,98.0,A98,51.0,CALCUTTA,Platimum,10001.0,C21,Normal Salary,100,3-Jan-04,SHOPPING,5000.50
1428,99.0,A99,35.0,CALCUTTA,Platimum,10002.0,C22,Self Employed,101,15-Jan-04,AIR TICKET,5001.00
1429,100.0,A100,36.0,COCHIN,Silver,100000.0,C5,Salaried_MNC,102,25-Jan-04,BUS TICKET,50000.00

####  c. Incase the repayment amount is more than the limit, replace the repayment with the limit.

In [85]:
customer_lim = pd.merge(left=customer_acqusition, right=repayment,on='Customer',how = 'inner')
customer_lim

,No,Customer,Age,City,Product,Limit,Company,Segment,Month,Amount
0,1.0,A1,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,12-Jan-04,495414.75
1,1.0,A1,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,3-Jan-04,245899.02
2,1.0,A1,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,15-Jan-04,259490.06
3,1.0,A1,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,25-Jan-04,437555.12
4,1.0,A1,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,17-Jan-05,165972.88
...,...,...,...,...,...,...,...,...,...,...
1425,96.0,A96,54.0,CHENNAI,Silver,100000.0,C19,Salaried_Pvt,25-Jan-04,310992.30
1426,97.0,A97,58.0,TRIVANDRUM,Platimum,10000.0,C20,Govt,12-Jan-04,121874.90
1427,98.0,A98,51.0,CALCUTTA,Platimum,10001.0,C21,Normal Salary,3-Jan-04,337815.57
1428,99.0,A99,35.0,CALCUTTA,Platimum,10002.0,C22,Self Employed,15-Jan-04,25682.73
1429,100.0,A100,36.0,COCHIN,Silver,100000.0,C5,Salaried_MNC,25-Jan-04,69551.19

In [86]:
customer_lim['Amount'] = np.where(customer_lim['Amount']>customer_lim['Limit'],customer_lim['Amount'].replace(to_replace=customer_lim['Limit']),customer_lim['Amount'])

In [87]:
customer_lim

,No,Customer,Age,City,Product,Limit,Company,Segment,Month,Amount
0,1.0,A1,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,12-Jan-04,495414.75
1,1.0,A1,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,3-Jan-04,245899.02
2,1.0,A1,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,15-Jan-04,259490.06
3,1.0,A1,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,25-Jan-04,437555.12
4,1.0,A1,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,17-Jan-05,165972.88
...,...,...,...,...,...,...,...,...,...,...
1425,96.0,A96,54.0,CHENNAI,Silver,100000.0,C19,Salaried_Pvt,25-Jan-04,310992.30
1426,97.0,A97,58.0,TRIVANDRUM,Platimum,10000.0,C20,Govt,12-Jan-04,121874.90
1427,98.0,A98,51.0,CALCUTTA,Platimum,10001.0,C21,Normal Salary,3-Jan-04,337815.57
1428,99.0,A99,35.0,CALCUTTA,Platimum,10002.0,C22,Self Employed,15-Jan-04,25682.73
1429,100.0,A100,36.0,COCHIN,Silver,100000.0,C5,Salaried_MNC,25-Jan-04,69551.19

#### 2. From the above dataset create the following summaries:
##### a. How many distinct customers exist?

In [17]:
customer_acqusition['Customer'].nunique()

95

#### b. How many distinct categories exist?

In [18]:
customer_acqusition['Segment'].nunique()

6

####  c. What is the average monthly spend by customers?

In [19]:
customer_spnd = spend.groupby(['Month','Customer'])['Amount'].mean().reset_index()
customer_spnd

         Month Customer     Amount
0     1-Apr-06      A14  341157.43
1     1-Apr-06      A21  265164.32
2     1-Apr-06      A22  258226.14
3     1-Apr-06      A24  164338.80
4     1-Apr-06      A27    8752.13
...        ...      ...        ...
1252  9-May-05       A5  161445.71
1253  9-May-05      A50  113481.37
1254  9-May-05      A57  324848.19
1255  9-May-05      A58   62814.73
1256  9-May-05       A8  371894.08

[1257 rows x 3 columns]

In [26]:
customer_spnd.dtypes

Month        object
Customer     object
Amount      float64
dtype: object

In [29]:
customer_spnd['Month'] = customer_spnd['Month'].apply(lambda x : pd.to_datetime(x))

In [30]:
customer_spnd['Spend_Month']=customer_spnd['Month'].apply(lambda x : x.month)

In [32]:
AvgMonthlySpend=customer_spnd.groupby(['Customer','Spend_Month'])[['Amount']].mean().reset_index()

In [33]:
AvgMonthlySpend

    Customer  Spend_Month        Amount
0         A1            1  341332.87700
1         A1            2  138421.15125
2         A1            4  261649.25000
3         A1            5  361141.31000
4         A1            8  344372.10000
..       ...          ...           ...
573      A95            1  240401.50000
574      A96            1   54729.66000
575      A97            1  139018.26000
576      A98            1  284521.06000
577      A99            1   90184.22000

[578 rows x 3 columns]

In [41]:
customer_lim.head()

  Customer      Month      Amount
0       A1   1-Apr-06  429099.970
1       A1   1-Feb-05   14473.410
2       A1  12-Jan-04  422930.785
3       A1  15-Jan-04  356258.850
4       A1  16-Feb-05  187398.640

#### d. What is the average monthly repayment by customers?

In [39]:
customer_lim=customer_lim.groupby(['Customer','Month'])[['Amount']].mean().reset_index()

In [42]:
customer_lim['Month'] = customer_lim['Month'].apply(lambda x : pd.to_datetime(x))

In [43]:
customer_lim['Repayment_Month']=customer_lim['Month'].apply(lambda x:x.month)

In [45]:
AvgMonthlyRepayment=customer_lim.groupby(['Customer','Repayment_Month'])[['Amount']].mean().reset_index()

In [46]:
AvgMonthlyRepayment

    Customer  Repayment_Month      Amount
0         A1                1  325723.331
1         A1                2  137713.785
2         A1                4  254474.580
3         A1                7  297176.740
4         A1                9  186427.500
..       ...              ...         ...
526      A95                1  369405.960
527      A96                1  310992.300
528      A97                1  121874.900
529      A98                1  337815.570
530      A99                1   25682.730

[531 rows x 3 columns]

####  E. If the monthly rate of interest is 2.9%, what is the profit for the bank for each month?  (Profit is defined as interest earned on Monthly Profit. Monthly Profit = Monthly repayment  â€“ Monthly spend. Interest is earned only on positive profits and not on negative amounts)

In [47]:
AvgMonthlyCustomers=pd.merge(left=AvgMonthlySpend,right=AvgMonthlyRepayment,left_on=['Customer','Spend_Month'],right_on=['Customer','Repayment_Month'])

In [48]:
AvgMonthlyCustomers['Monthly_Profit']=AvgMonthlyCustomers.Amount_y-AvgMonthlyCustomers.Amount_x

In [49]:
AvgMonthlyCustomers['Profit']=np.where(AvgMonthlyCustomers['Monthly_Profit']>0,AvgMonthlyCustomers['Monthly_Profit']*2.9/100,np.nan)

In [50]:
AvgMonthlyCustomers

,Customer,Spend_Month,Amount_x,Repayment_Month,Amount_y,Monthly_Profit,Profit
0,A1,1,341332.87700,1,325723.331000,-15609.546000,NaN
1,A1,2,138421.15125,2,137713.785000,-707.366250,NaN
2,A1,4,261649.25000,4,254474.580000,-7174.670000,NaN
3,A1,11,183839.61000,11,285729.090000,101889.480000,2954.794920
4,A10,1,173828.28250,1,283324.721667,109496.439167,3175.396736
...,...,...,...,...,...,...,...
426,A95,1,240401.50000,1,369405.960000,129004.460000,3741.129340
427,A96,1,54729.66000,1,310992.300000,256262.640000,7431.616560
428,A97,1,139018.26000,1,121874.900000,-17143.360000,NaN
429,A98,1,284521.06000,1,337815.570000,53294.510000,1545.540790
430,A99,1,90184.22000,1,25682.730000,-64501.490000,NaN

#### f. What are the top 5 product types?

In [51]:
spend.groupby('Type').Amount.sum().reset_index().sort_values(by='Amount',ascending = False)

            Type       Amount
10         PETRO  49863174.09
4         CAMERA  41481571.96
7           FOOD  37773338.43
14  TRAIN TICKET  33067077.15
0     AIR TICKET  32955445.42
13      SHOPPING  28210354.51
6        CLOTHES  24651102.49
3     BUS TICKET  24554787.97
8      JEWELLERY  22242396.96
9   MOVIE TICKET  19644829.93
11        RENTAL  16949227.44
2           BIKE  11551105.59
1           AUTO   8008084.04
5            CAR   7280324.89
12       SANDALS   6411253.32

#### g. Which city is having maximum spend?

In [52]:
customer_spend.groupby('City').Amount.sum().reset_index().sort_values(by='Amount',ascending = False)

         City       Amount
2    CALCUTTA  41108132.30
4      COCHIN  38624218.06
0   BANGALORE  31998057.56
1      BOMBAY  28593126.38
3     CHENNAI  22128635.65
7  TRIVANDRUM  15277490.39
6       PATNA  15260586.97
5       DELHI  10918286.54

#### h. Which age group is spending more money?

In [53]:
customer_spend['Age_Group']=np.where(((customer_spend.Age.astype(int) >= 18) & (customer_spend.Age.astype(int) < 25)), 'Youth',np.where(((customer_spend.Age.astype(int) >= 25) & (customer_spend.Age.astype(int) < 65)), 'Adult','Senior'))
customer_spend.groupby('Age_Group').Amount.sum()

Age_Group
Adult     1.515455e+08
Senior    3.768249e+07
Youth     1.468050e+07
Name: Amount, dtype: float64

#### i. Who are the top 10 customers in terms of repayment?

In [54]:
customer_lim.groupby('Customer').Amount.sum().reset_index().sort_values(by = 'Amount', ascending = False).head(10)

   Customer        Amount
5       A13  8.191193e+06
56      A61  7.872576e+06
14      A22  7.686203e+06
41      A48  7.560054e+06
38      A45  7.472656e+06
13      A21  7.216547e+06
4       A12  7.148908e+06
36      A43  7.052010e+06
30      A37  7.050661e+06
39      A46  6.837834e+06

In [55]:
import datetime

#### 3. Calculate the city wise spend on each product on yearly basis. Also include a graphical representation for the same.

In [57]:
customer_spend

,No,Customer,Age,City,Product,Limit,Company,Segment,Sl No:,Month,Type,Amount,Age_Group
0,1.0,A1,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,1,12-Jan-04,JEWELLERY,485470.80,Senior
1,1.0,A1,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,2,3-Jan-04,PETRO,410556.13,Senior
2,1.0,A1,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,3,15-Jan-04,CLOTHES,23740.46,Senior
3,1.0,A1,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,4,25-Jan-04,FOOD,484342.47,Senior
4,1.0,A1,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,5,17-Jan-05,CAMERA,369694.07,Senior
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1425,96.0,A96,54.0,CHENNAI,Silver,100000.0,C19,Salaried_Pvt,98,25-Jan-04,BIKE,54729.66,Adult
1426,97.0,A97,58.0,TRIVANDRUM,Platimum,10000.0,C20,Govt,99,12-Jan-04,AUTO,5000.00,Adult
1427,98.0,A98,51.0,CALCUTTA,Platimum,10001.0,C21,Normal Salary,100,3-Jan-04,SHOPPING,5000.50,Adult
1428,99.0,A99,35.0,CALCUTTA,Platimum,10002.0,C22,Self Employed,101,15-Jan-04,AIR TICKET,5001.00,Adult
1429,100.0,A100,36.0,COCHIN,Silver,100000.0,C5,Salaried_MNC,102,25-Jan-04,BUS TICKET,50000.00,Adult

In [64]:
customer_spend['Month'] = customer_spend['Month'].apply(lambda x: pd.to_datetime(x))

In [63]:
customer_spend.dtypes

No                   float64
Customer              object
Age                  float64
City                  object
Product               object
Limit                float64
Company               object
Segment               object
Sl No:                 int64
Month                 object
Type                  object
Amount               float64
Age_Group             object
year_spend    datetime64[ns]
dtype: object

In [65]:
customer_spend['year_spend']=customer_spend['Month'].apply(lambda x:x.year)

In [70]:
City_Wise_spend = pd.pivot_table(data = customer_spend, index = 'City', columns=['Product','year_spend'], 
               values='Amount', aggfunc='sum')

In [73]:
City_Wise_spend

Product           Gold                              Platimum              \
year_spend        2004         2005         2006        2004        2005
City
BANGALORE   7460145.61   8706615.03   9582502.52  1112732.30   912284.97
BOMBAY      6987853.53   8983018.28   7917144.31   897264.94   706804.44
CALCUTTA    7477140.98  10303355.80  11167532.77  2037690.30  4434696.31
CHENNAI     1059618.50   3740945.58   2704288.62  3535652.38  5053956.32
COCHIN      7315850.15  12110613.03  10234260.11  2199994.82  1278274.70
DELHI       2806495.00   1964845.27   2957103.32   283512.89   494157.86
PATNA       2072567.90   3252615.77   2276181.69  1113069.60  2883231.07
TRIVANDRUM  2415102.84   1240375.85   2735710.87  2161676.67  3601443.30

Product                     Silver
year_spend        2006        2004       2005        2006
City
BANGALORE    685831.27  1291852.58  830612.34  1415480.94
BOMBAY       967129.51   532089.03  508988.54  1092833.80
CALCUTTA    3589606.66   500006.00  440147.06  1157956.42
CHENNAI     5024923.40   282056.86  377184.49   350009.50
COCHIN      2748735.38   814229.62  652269.38  1269990.87
DELHI        176788.72   768172.30  612311.21   854899.97
PATNA       1256137.65   756684.10  950094.19   700005.00
TRIVANDRUM  2147403.75   200002.00  269912.99   505862.12

# 4. Create graphs for
## a. Monthly comparison of total spends, city wise

In [74]:
customer_spend['Month'] = pd.DatetimeIndex(customer_spend['Month']).month
pd.pivot_table(data = customer_spend, index = 'City', columns='Month', 
               values='Amount', aggfunc='sum').plot(kind='bar',stacked=True)

## b. Comparison of yearly spend on air tickets

In [76]:
pd.pivot_table(data = customer_spend[customer_spend.Type=='AIR TICKET'], index = 'Type', columns='year_spend', 
               values='Amount', aggfunc='sum').plot(kind='bar')

## c. Comparison of monthly spend for each product (look for any seasonality that exists in terms of spend)

In [77]:
pd.pivot_table(data = customer_spend, index = 'Product', columns='Month', 
               values='Amount', aggfunc='sum').plot(kind='bar')

## 5. Write user defined PYTHON function to perform the following analysis:You need to find top 10 customers for each city in terms of their repayment amount by different products and by different time periods i.e. year or month. The user should be able to specify the product (Gold/Silver/Platinum) and time period (yearly or monthly) and the function should automatically take these inputs while identifying the top 10 customers.

In [80]:
customer_lim.head()

  Customer      Month      Amount  Repayment_Month
0       A1 2006-04-01  429099.970                4
1       A1 2005-02-01   14473.410                2
2       A1 2004-01-12  422930.785                1
3       A1 2004-01-15  356258.850                1
4       A1 2005-02-16  187398.640                2

     Customer      Month     Amount
0          A1  12-Jan-04  495414.75
1          A1   3-Jan-04  245899.02
2          A1  15-Jan-04  259490.06
3          A1  25-Jan-04  437555.12
4          A1  17-Jan-05  165972.88
...       ...        ...        ...
1495      A67   9-May-05   55638.77
1496      A68  10-May-06  319836.49
1497      A69  11-Jul-06  247628.45
1498      A70  12-Aug-05  454016.51
1499      A71  13-Sep-04   56286.33

[1500 rows x 3 columns]

In [90]:
customer_lim['Year'] = pd.DatetimeIndex(customer_lim['Month']).year
def top10Customers(product_category,time_period):    
    return customer_lim.loc[(customer_lim.Product == product_category)].groupby(['Customer','City','Product',time_period]).Amount.sum().nlargest(n=10).reset_index().sort_values('Amount',ascending=False)

product_category=str(input("Please Enter Product Category (Gold/Silver/Platinum): "))
time_period=str(input("Please Enter Time Period (Year/Month): "))
Customers=top10Customers(product_category,time_period)
Customers

Please Enter Product Category (Gold/Silver/Platinum): Gold
Please Enter Time Period (Year/Month): Year

  Customer        City Product  Year      Amount
0      A61      COCHIN    Gold  2005  4276860.55
1      A44       DELHI    Gold  2005  4165317.77
2      A45      COCHIN    Gold  2005  4042447.57
3      A43   BANGALORE    Gold  2005  4006956.60
4      A13   BANGALORE    Gold  2005  3757673.00
5      A61      COCHIN    Gold  2006  3744127.41
6      A60    CALCUTTA    Gold  2005  3742856.10
7      A13   BANGALORE    Gold  2006  3477314.89
8      A29    CALCUTTA    Gold  2006  3434298.00
9      A28  TRIVANDRUM    Gold  2006  3376614.65